# Generated by Django 3.2.7 on 2021-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
